
logging:
  level:
    root: info
    com.hao: debug

spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://192.168.0.122:3306/shirojwt?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
          username: root
          password: 123456
          driverClassName: com.mysql.jdbc.Driver
        slave:
          url: jdbc:mysql://192.168.0.122:3306/shirojwt?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
          username: root
          password: 123456
          driverClassName: com.mysql.jdbc.Driver
      hikari:
        #最小空闲连接数量
        minIdle: 5
        #空闲连接存活最大时间，默认600000（10分钟）
        idleTimeout: 180000
        #连接池最大连接数，默认是10
        maxPoolSize: 10
        #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        isAutoCommit: true
        #连接池母子
        poolName: ShiroJwtHikariCP
        #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        maxLifetime: 1800000
        #数据库连接超时时间,默认30秒，即30000
        connectionTimeout: 30000
        connectionTestQuery: SELECT 1

redis:
  database: 1
  host: 192.168.0.122
  port: 6379
  password: lym123..
  timeout: 10000
  pool:
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 10
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 100
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1

pool:
  corePoolSize: 3
  maxPoolSize: 3
  keepAliveTime: 0
  queueNum: 100